/* -*- Mode: Java; tab-width: 2; indent-tabs-mode:nil; c-basic-offset: 2 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

var selfData = require("sdk/self").data,
  pageMod = require("sdk/page-mod"),
  prefs = require('sdk/simple-prefs').prefs,
  LaTeXML = require("./LaTeXML"),
  TeXZilla = require("./TeXZilla");

function TeXZillaFromLaTeX(aWorker, aLaTeX)
{
  var json = { input: aLaTeX };
  try {
    json.output = TeXZilla.toMathMLString(aLaTeX, false, false, true);
    aWorker.port.emit("fromLaTeX-response", json);
    return true;
  } catch (e) { console.log(e); }
  return false;
}

function addWorker(aWorker)
{
  aWorker.port.on("fromLaTeX-request", function(aLaTeX) {
    // Conversion strategies
    // T = TeXZilla
    // L = LaTeXML
    // TL = TeXZilla, LaTeXML
    // LT = LaTeXML, TeXZilla
    var s = prefs["strategy"];
    if (s === "T" || s === "TL") {
      // We try to convert the LaTeX source with our local copy of TeXZilla.
      if (TeXZillaFromLaTeX(aWorker, aLaTeX)) {
        return;
      }
    }
    if (s === "L" || s === "TL" || s === "LT") {
      // Now we try to convert the LaTeX source with a remote LaTeX instance.
      LaTeXML.fromLaTeX(aWorker, aLaTeX, function(aJSON) {
        if (!aJSON.output && prefs["strategy"] === "LT") {
          // If the LaTeXML conversion failed, we try TeXZilla.
          if (TeXZillaFromLaTeX(aWorker, aLaTeX)) {
            return;
          }
        }
        aWorker.port.emit("fromLaTeX-response", aJSON);
      });
    }
  });
}

// WordPress LaTeX plugin
// See http://en.support.wordpress.com/latex/
pageMod.PageMod({
  include: [
   "*.wordpress.com",
  ],
  contentScriptFile: [
    selfData.url("convert.js"),
    selfData.url("generic-latex-1.js")
  ],
  onAttach: addWorker,
  contentScriptOptions: "img.latex"
});

// Images generated by texvc.
// https://www.mediawiki.org/wiki/Texvc
pageMod.PageMod({
  include: [
    "*.wikipedia.org",
    /.*en\.academic\.ru\/dic\.nsf\/enwiki.*/
  ],
  contentScriptFile: [
    selfData.url("convert.js"),
    selfData.url("texvc.js")
  ],
  onAttach: addWorker
});

// Images generated by gladTeX.
pageMod.PageMod({
  include: [
   "*.myphysicslab.com",
  ],
  contentScriptFile: [
    selfData.url("convert.js"),
    selfData.url("generic-latex-1.js")
  ],
  onAttach: addWorker,
  contentScriptOptions: ".inline_eqn > img, .display_eqn > img"
});

// Spip
// See http://www.spip.net/en_article3563.html
pageMod.PageMod({
  include: [
   "*.spip.net",
  ],
  contentScriptFile: [
    selfData.url("convert.js"),
    selfData.url("generic-latex-1.js")
  ],
  onAttach: addWorker,
  contentScriptOptions: ".spip img"
});

pageMod.PageMod({
  include: [
   "*.les-mathematiques.net"
  ],
  contentScriptFile: [
    selfData.url("convert.js"),
    selfData.url("generic-latex-2.js")
  ],
  onAttach: addWorker,
  contentScriptOptions: "img"
});
