/* -*- Mode: Java; tab-width: 2; indent-tabs-mode:nil; c-basic-offset: 2 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

"use strict";

exports.predefinedRules = [
  {
    // WordPress LaTeX plugin
    // See http://en.support.wordpress.com/latex/
    Script: "generic-latex-1.js",
    ScriptOptions: "img.latex",
    URIPatternList: "http://en.support.wordpress.com/latex/"
  },
  {
    // Images generated by texvc.
    // See https://www.mediawiki.org/wiki/Texvc
    Script: "texvc.js",
    URIPatternList: [
      "*.wikipedia.org",
      "http://en.academic.ru/dic.nsf/enwiki/*"
    ]
  },
  {
    // Images generated by gladTeX.
    Script: "generic-latex-1.js",
    ScriptOptions: ".inline_eqn > img, .display_eqn > img",
    URIPatternList: "http://myphysicslab.com/*"
  },
  {
    // Spip
    // See http://www.spip.net/en_article3563.html
    Script: "generic-latex-1.js",
    ScriptOptions: ".spip img",
    URIPatternList: "http://www.spip.net/*"
  },
  {
    Script: "generic-latex-2.js",
    ScriptOptions: "img",
    URIPatternList: "http://www.les-mathematiques.net/*"
  }
];
